#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ldappool
Version  : 1.0
Release  : 13
URL      : https://pypi.python.org/packages/source/l/ldappool/ldappool-1.0.tar.gz
Source0  : https://pypi.python.org/packages/source/l/ldappool/ldappool-1.0.tar.gz
Summary  : A connection pool for python-ldap
Group    : Development/Tools
License  : MPL-1.1 GPL-2.0 LGPL-2.1
Requires: ldappool-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
ldappool
========
A simple connector pool for python-ldap.
The pool keeps LDAP connectors alive and let you reuse them,
drastically reducing the time spent to initiate a ldap connection.

%package python
Summary: python components for the ldappool package.
Group: Default

%description python
python components for the ldappool package.


%prep
%setup -q -n ldappool-1.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
